# This is a TOML configuration file.

# Connection details of ethereum blockchain.
[ethereum]
  URL = ""
  URLRPC = ""

  [ethereum.account]
    KeyFile = ""

  # Addresses of contracts deployed on ethereum blockchain.
  [ethereum.ContractAddresses]
    BondedECDSAKeepFactory = ""

# Addresses of applications approved by the operator.
[SanctionedApplications]
  Addresses = [""]

[LibP2P]
  Peers = []
  Port = ""
  AnnouncedAddresses = []

[Storage]
    DataDir = ""
