# This is a TOML configuration file.

# Connection details of ethereum blockchain.
[ethereum]
  URL = "Set by Kube"

[ethereum.account]
  KeyFile = "Set by Kube"

# Addresses of contracts deployed on ethereum blockchain.
[ethereum.ContractAddresses]
  BondedECDSAKeepFactory = "Set by Kube"

[Storage]
    DataDir = "Set by Kube"
